version: 2.1

jobs:
  docker_build_and_deploy:
    executor: docker/docker
    description: Build the docker image and push it to the docker hub registry.
    parameters:
      cmake_version:
        type: string
      gcc_version:
        type: integer
    steps:
      - checkout

      # login to docker hub registry
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: ./scripts/build.sh -c << parameters.cmake_version >> -g << parameters.gcc_version >> -u $DOCKER_USER .

      # deploy the image
      - run: ./scripts/push.sh -c << parameters.cmake_version >> -g << parameters.gcc_version >> -u $DOCKER_USER

orbs:
  docker: circleci/docker@1.0.1
  
workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker_build_and_deploy:
          filters:
            branches:
              only: 'master'
          matrix:
            parameters:
              cmake_version: ["3.15.7", "3.14.7", "3.13.5", "3.12.4", "3.11.4", "3.10.3", "3.9.6", "3.8.2", "3.7.2", "3.6.3"]
              gcc_version: ["10", "9", "8", "7", "6"]
      
