version: 2.1
commands:
  docker_build_and_deploy:
    description: Build the docker image and push it to the docker hub registry.
    parameters:
      cmake_version:
        type: string
      gcc_version:
        type: string
    steps:
      - checkout

      # login to docker hub registry
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: ./scripts/build.sh -c << parameters.cmake_version >> -g << parameters.gcc_version >> -u $DOCKER_USER .

      # deploy the image
      - run: docker push $DOCKER_USER/$FOLDER:$VERSION
jobs:
  
  # == GCC 6 ====================================
  gcc6-cmake:3.6.3:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.6.3
          gcc_version: 6
  gcc6-cmake:3.7.2:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.7.2
          gcc_version: 6
  gcc6-cmake:3.8.2:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.8.2
          gcc_version: 6
  gcc6-cmake:3.9.6:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.9.6
          gcc_version: 6
  
  # == GCC 7 ====================================
  gcc7-cmake:3.6.3:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.6.3
          gcc_version: 7
  gcc7-cmake:3.7.2:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.7.2
          gcc_version: 7
  gcc7-cmake:3.8.2:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.8.2
          gcc_version: 7
  gcc7-cmake:3.9.6:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.9.6
          gcc_version: 7
  gcc7-cmake:3.10.3:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.10.3
          gcc_version: 7
  
  # == GCC 8 ====================================
  gcc8-cmake:3.9.6:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.9.6
          gcc_version: 8
  gcc8-cmake:3.10.3:
    machine: true
    steps:
      - docker_build_and_deploy:
          cmake_version: 3.10.3
          gcc_version: 8

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - gcc6-cmake:3.6.3
      - gcc6-cmake:3.7.2
      - gcc6-cmake:3.8.2
      - gcc6-cmake:3.9.6
      - gcc7-cmake:3.6.3
      - gcc7-cmake:3.7.2
      - gcc7-cmake:3.8.2
      - gcc7-cmake:3.9.6
      - gcc7-cmake:3.10.3
      - gcc8-cmake:3.9.6
      - gcc8-cmake:3.10.3


