version: 2.1

jobs:
  docker_build_and_deploy:
    description: Build the docker image and push it to the docker hub registry.
    parameters:
      cmake_version:
        type: string
      gcc_version:
        type: integer
    machine: true
    steps:
      - checkout

      # login to docker hub registry
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      # build the application image
      - run: ./scripts/build.sh -c << parameters.cmake_version >> -g << parameters.gcc_version >> -u $DOCKER_USER .

      # deploy the image
      - run: ./scripts/push.sh -c << parameters.cmake_version >> -g << parameters.gcc_version >> -u $DOCKER_USER
  
workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker_build_and_deploy:
          filters:
            branches:
              only: 'master'
          matrix:
            parameters:
              cmake_version: ["3.15.7", "3.14.7", "3.13.5", "3.12.4", "3.11.4", "3.10.3", "3.9.6", "3.8.2", "3.7.2", "3.6.3"]
              gcc_version: [10, 9, 8, 7, 6]
      
